version: '3'

services:
  postgres:
    container_name: assetdb_postgres
    image: postgres:latest
    restart: always
    env_file: .env.local
    ports:
      - "5432:5432"

volumes:
  postgres-db:
    driver: local
